drop database asrcinema;
create database asrcinema;
use asrcinema;


CREATE TABLE RUOLO(
ID_RUOLO INT not null primary key auto_increment,
RUOLO VARCHAR(50)
);

CREATE TABLE UTENTE(
ID_UTENTE INT not null primary key auto_increment,
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50),
ID_RUOLO INTEGER,
FOREIGN KEY (ID_RUOLO) REFERENCES RUOLO(ID_RUOLO),
UNIQUE(EMAIL)
);

CREATE TABLE PREZZO(
ID_PREZZO INT not null primary key auto_increment,
TIPO VARCHAR(50),
PREZZO DOUBLE
);

CREATE TABLE SALA(
ID_SALA INT not null primary key auto_increment,
NOME VARCHAR(50),
DESCRIZIONE VARCHAR(50)
);

CREATE TABLE POSTO(
ID_POSTO INT not null primary key auto_increment,
ID_SALA INTEGER,
RIGA CHAR(1),
COLONNA INTEGER,
FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA)
);

CREATE TABLE GENERE(
ID_GENERE INT not null primary key auto_increment,
DESCRIZIONE VARCHAR(50)
);

CREATE TABLE FILM(
ID_FILM INT not null primary key auto_increment,
ID_GENERE INTEGER,
TITOLO VARCHAR(100),
DURATA integer,
TRAMA VARCHAR(1000),
URL_TRAILER VARCHAR(255),
URI_LOCANDINA VARCHAR(255),
IS_IN_SLIDER BOOLEAN,
ANNO INT,
REGISTA VARCHAR(255),
FOTO_SL VARCHAR(255),
FOREIGN KEY (ID_GENERE) REFERENCES GENERE(ID_GENERE)
);

CREATE TABLE SPETTACOLO(
ID_SPETTACOLO INT not null primary key auto_increment,
ID_FILM INTEGER,
ID_SALA INTEGER,
DATA_ORA TIMESTAMP,
FOREIGN KEY (ID_FILM) REFERENCES FILM(ID_FILM),
FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA)
);

CREATE TABLE PRENOTAZIONE(
ID_PRENOTAZIONE INT not null primary key auto_increment,
ID_UTENTE INTEGER,
ID_SPETTACOLO INTEGER,
ID_PREZZO INTEGER,
ID_POSTO INTEGER,
DATA_ORA_OPERAZIONE TIMESTAMP,
UNIQUE (ID_POSTO,ID_SPETTACOLO),
FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID_UTENTE),
FOREIGN KEY (ID_SPETTACOLO) REFERENCES SPETTACOLO(ID_SPETTACOLO),
FOREIGN KEY (ID_PREZZO) REFERENCES PREZZO(ID_PREZZO),
FOREIGN KEY (ID_POSTO) REFERENCES POSTO(ID_POSTO)
);



