use asrcinema;

INSERT INTO PREZZO (TIPO, PREZZO)
VALUES('Intero', 9.00);

INSERT INTO PREZZO (TIPO, PREZZO)
VALUES('Ridotto', 6.00);

INSERT INTO PREZZO (TIPO, PREZZO)
VALUES('Militari', 5.00);

INSERT INTO PREZZO (TIPO, PREZZO)
VALUES('Disabili', 5.00);
