use asrcinema;

INSERT INTO SALA (NOME, DESCRIZIONE)
VALUES ('SALA1','Sala da 96 posti');

INSERT INTO SALA (NOME, DESCRIZIONE)
VALUES ('SALA2','Sala da 96 posti');

INSERT INTO SALA (NOME, DESCRIZIONE)
VALUES ('SALA3','Sala da 96 posti');

INSERT INTO SALA (NOME, DESCRIZIONE)
VALUES ('SALA4','Sala da 96 posti');

INSERT INTO SALA (NOME, DESCRIZIONE)
VALUES ('SALA5','Sala da 96 posti');

